name: Publish Rock

on:
  workflow_call:

jobs:
  publish-image:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v6
        with:
          name: ella-core-tester-${{ matrix.arch }}

      - name: Import and push to github package (${{ matrix.arch }})
        run: |
          version="$(yq '.version' rockcraft.yaml)"
          docker load -i ella-core-tester-${{ matrix.arch }}.tar
          docker tag ella-core-tester:latest ghcr.io/ellanetworks/ella-core-tester:${version}-${{ matrix.arch }}
          docker push ghcr.io/ellanetworks/ella-core-tester:${version}-${{ matrix.arch }}

  make-manifest:
    needs: publish-image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          version="$(yq '.version' rockcraft.yaml)"

          docker manifest create ghcr.io/ellanetworks/ella-core-tester:${version} \
            ghcr.io/ellanetworks/ella-core-tester:${version}-amd64 \
            ghcr.io/ellanetworks/ella-core-tester:${version}-arm64

          docker manifest create ghcr.io/ellanetworks/ella-core-tester:latest \
            ghcr.io/ellanetworks/ella-core-tester:${version}-amd64 \
            ghcr.io/ellanetworks/ella-core-tester:${version}-arm64

          docker manifest push ghcr.io/ellanetworks/ella-core-tester:${version}
          docker manifest push ghcr.io/ellanetworks/ella-core-tester:latest
