name: Publish Rock (PR)

on:
  workflow_call:

jobs:
  publish-image:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v7
        with:
          name: ella-core-tester-${{ matrix.arch }}

      - name: Import and push to github package (${{ matrix.arch }})
        run: |
          version="$(yq '.version' rockcraft.yaml)"
          tag="pr-${{ github.event.pull_request.number }}"
          docker load -i ella-core-tester-${{ matrix.arch }}.tar
          docker tag ella-core-tester:latest ghcr.io/ellanetworks/ella-core-tester:${tag}-${{ matrix.arch }}
          docker push ghcr.io/ellanetworks/ella-core-tester:${tag}-${{ matrix.arch }}

  make-manifest:
    needs: publish-image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          tag="pr-${{ github.event.pull_request.number }}"

          docker manifest create ghcr.io/ellanetworks/ella-core-tester:${tag} \
            ghcr.io/ellanetworks/ella-core-tester:${tag}-amd64 \
            ghcr.io/ellanetworks/ella-core-tester:${tag}-arm64

          docker manifest push ghcr.io/ellanetworks/ella-core-tester:${tag}
